#Build Status Badge: ![](https://github.com/prafulla-chaudhari/githubactiontutorials/edit/main/.github/workflows/badge.svg)
name: Branding hello-world
on: [push]
jobs:
  job1:
    name: Branding hello-display
    runs-on: ubuntu-latest
    steps:
          - name: Branding display hello
            uses: actions/checkout@v2
          - run: |
              mkdir download
              cd download
              echo  "hello" > a.html
          - run:  ls
          - run:  |
                cd download
                ls
          - run: echo  "${{github.workspace}}"
          - name: Branding Upload Artifact
            uses: actions/upload-artifact@v2
            with:
               name: Branding hi-Artifact
               path: download
  job2:
    name: Branding hi-display
    runs-on: ubuntu-latest
    steps:
          - name: Branding display hi
            uses: actions/checkout@v2
          - run: |
              mkdir download
              cd download
              echo  "hi" > b.html
          - run:  ls
          - run:  |
                cd download
                ls
          - run: echo  "${{github.workspace}}"
          - name: Branding Upload Artifact
            uses: actions/upload-artifact@v2
            with:
               name: Branding hi-Artifact
               path: download
