name: hello-world
on: [push]
jobs:
  job1:
    name: hello-display
    runs-on: ubuntu-latest
    steps:
          - name: display hello
            uses: actions/checkout@v2
          - run: |
              mkdir download
              cd download
              echo  "hello" > a.html
          - run:  ls
          - run:  |
                cd download
                ls
          - run: echo  "${{github.workspace}}"
          - name: Upload Artifact
            uses: actions/upload-artifact@v2
            with:
               name: hi-Artifact
               path: download
  job2:
    name: hi-display
    runs-on: ubuntu-latest
    steps:
          - name: display hi
            uses: actions/checkout@v2
          - run: |
              mkdir download
              cd download
              echo  "hi" > b.html
          - run:  ls
          - run:  |
                cd download
                ls
          - run: echo  "${{github.workspace}}"
          - name: Upload Artifact
            uses: actions/upload-artifact@v2
            with:
               name: test-Artifact
               path: download
  job3:
      name: download-display
      runs-on: ubuntu-latest
      needs: [job1,job2]
      steps:
           
           - name: Download Artifact
             uses: actions/download-artifact@v2
             with:
                name: test-Artifact

