name: hello-world
on: [push]
jobs:
  job1:
    name: hello-display
    runs-on: ubuntu-latest
    steps:
          - name: display hello
            uses: actions/checkout@v2
          - run: echo  "hello"
  job2:
    needs: job1
    name: hi-display
    runs-on: ubuntu-latest
    steps:
      - name: display hi
        uses : actions/checkout@v2
      - run: echo "hi"
  job3:
      needs: job2
      name: Upload artifact
      runs-on: ubuntu-latest
      steps:
        - name: Upload Artifact
          uses: actions/upload-artifact@v2
          with:
              name: hi-Artifact
              path: ./arti
  
