name: hello-world
on: [push]
jobs:
  job1:
    name: hello-display
    runs-on: ubuntu-latest
    steps:
          - name: display hello
            uses: actions/checkout@v2
          - run: echo  "hello"
