name: hello-world
on: [push]
jobs:
  job1:
    name: hello-display
    runs-on: ubuntu-latest
    steps:
          - name: display hello
            uses: actions/checkout@v2
          - run: |
              mkdir download
              cd download
              echo  "hello" > a.html
          - run:  ls
          - run:  |
                cd download
                ls
          - run: echo  "${{github.workspace}}"
  
  job3:
      needs: job2
      name: Upload artifact
      runs-on: ubuntu-latest
      steps:
        - name: Upload Artifact
          uses: actions/upload-artifact@v2
          with:
              name: hi-Artifact
              path: download
  
